name: Sync Translations

on:
  push:
    branches:
      - '**' 
    paths:
      - 'custom_components/geozones/strings.json'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_WORKFLOW_SECRET }}

      - name: Copy strings.json to translations/en.json
        run: |
          cp custom_components/geozones/strings.json custom_components/geozones/translations/en.json

      - name: Commit & Push changes if needed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: sync translations/en.json with strings.json"
          file_pattern: "custom_components/geozones/translations/en.json"
